version: '2'
services:
  quotes:
    build:
      context: ./QuoteService
      dockerfile: Dockerfile
  api:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    environment:
      - "QUOTES_API=http://quotes:5000"
    depends_on:
      - quotes
    ports:
      - "3000:3000"
  frontend:
    build:
      context: ./FrontendApplication
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    